### ISSUE TITLE
ModuleNotFoundError: No module named 'ffmpeg'

### ISSUE THREAD

**Issue by tomboolean** [GoogleCloudPlatform/functions-framework-python#176]
```bash
(env) anatomboulian@Anas-MacBook-Pro cf-combine-audio % python3
Python 3.9.9 (main, Nov 21 2021, 03:23:44)
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ffmpeg
>>> quit()
(env) anatomboulian@Anas-MacBook-Pro cf-combine-audio % pip freeze
black==22.1.0
certifi==2021.10.8
charset-normalizer==2.0.11
click==8.0.3
ffmpeg-python==0.2.0
Flask==2.0.2
future==0.18.2
google-cloud==0.34.0
idna==3.3
itsdangerous==2.0.1
Jinja2==3.0.3
MarkupSafe==2.0.1
mypy-extensions==0.4.3
pathspec==0.9.0
platformdirs==2.5.0
pydantic==1.9.0
pyee==9.0.4
python-dotenv==0.19.2
python-ffmpeg==1.0.13
requests==2.27.1
tomli==2.0.1
typing_extensions==4.0.1
urllib3==1.26.8
Werkzeug==2.0.3
xmltodict==0.12.0
(env) anatomboulian@Anas-MacBook-Pro cf-combine-audio % ./scripts/run-local-pubsub.sh
Traceback (most recent call last):
  File "/usr/local/bin/functions-framework", line 8, in <module>
    sys.exit(_cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/functions_framework/_cli.py", line 37, in _cli
    app = create_app(target, source, signature_type)
  File "/usr/local/lib/python3.9/site-packages/functions_framework/__init__.py", line 288, in create_app
    spec.loader.exec_module(source_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/anatomboulian/git/cf-combine-audio/src/main.py", line 12, in <module>
    import ffmpeg
```

./scripts/run-local-pubsub.sh's contents:

```bash
#! /bin/bash

ROOT="$( pwd )"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

SOURCE_FILE="src/main.py"

source "${ROOT}/.env"

functions-framework \
  --source=${SOURCE_FILE} \
  --target=${FUNCTION_NAME_PUBSUB} \
  --signature-type=event \
  --port=${FUNCTION_PORT_PUBSUB} \
  --debug
```

 .src/requirements.txt contents:

```
ffmpeg-python==0.2.0
Flask==2.0.2
google-cloud==0.34.0
pydantic==1.9.0
python-dotenv==0.19.2
requests==2.27.1
xmltodict==0.12.0
```

.src/main.py's contents:

```python3
import base64
from typing import Optional
import json
import logging


from flask import current_app, escape

from pydantic import BaseModel

import ffmpeg

logging.basicConfig(level=logging.NOTSET)


log = logging.getLogger(__name__)

log.info(f"Cold started.")


class AudioReady(BaseModel):
    call_id: str
    partial_id: str
    audio_partial_id: str


def combine_audio_http(request):
    """HTTP Cloud Function.
    Args:
        request (flask.Request): The request object.
        <http://flask.pocoo.org/docs/1.0/api/#flask.Request>
    Returns:
        The response text, or any set of values that can be turned into a
        Response object using `make_response`
        <http://flask.pocoo.org/docs/1.0/api/#flask.Flask.make_response>.
    """
    subject = request.args.get("subject", "World")
    subject = escape(subject)

    return f"Hello, {subject}!"


def combine_audio_pubsub(event, context):
    """Background Cloud Function to be triggered by Pub/Sub.
    Args:
         event (dict):  The dictionary with data specific to this type of
         event. The `data` field contains the PubsubMessage message. The
         `attributes` field will contain custom attributes if there are any.
         context (google.cloud.functions.Context): The Cloud Functions event
         metadata. The `event_id` field contains the Pub/Sub message ID. The
         `timestamp` field contains the publish time.
    """
    global peerlogic_api_client

    log = current_app.logger

    log.info(f"Started! Combine Audio - Stereo. Event: {event}, Context: {context}")

```

As you can see, we import pydantic just fine without issue. Can someone tell me,  what is the problem here?

**Comment by tomboolean** [comment]
This is also happening with pydub.

```
(env) anatomboulian@Anas-MacBook-Pro cf-combine-audio % python3
Python 3.9.9 (main, Nov 21 2021, 03:23:44)
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pydub
>>> quit()
(env) anatomboulian@Anas-MacBook-Pro cf-combine-audio % ./scripts/run-local-pubsub.sh
Traceback (most recent call last):
  File "/usr/local/bin/functions-framework", line 8, in <module>
    sys.exit(_cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/functions_framework/_cli.py", line 37, in _cli
    app = create_app(target, source, signature_type)
  File "/usr/local/lib/python3.9/site-packages/functions_framework/__init__.py", line 288, in create_app
    spec.loader.exec_module(source_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/anatomboulian/git/cf-combine-audio/src/main.py", line 12, in <module>
    from audio_conversion import combine_wavefiles_together, wav_codec_to_pcm_s16le
  File "/Users/anatomboulian/git/cf-combine-audio/src/audio_conversion.py", line 8, in <module>
    from pydub import AudioSegment
ModuleNotFoundError: No module named 'pydub'
(env) anatomboulian@Anas-MacBook-Pro cf-combine-audio %
```

**Comment by asriniva** [comment]
What does the shebang for `functions-framework` say? I suspect it might be pulling the wrong Python environment (so ffmpeg is not present there).

**Comment by asriniva** [comment]
Closing due to inactivity.
