### ISSUE TITLE
Flask Celery worker raise RuntimeError(unbound_message) from None RuntimeError: Working outside of request context.

### ISSUE THREAD

**Issue by AnandHiremath** [GoogleCloudPlatform/functions-framework-python#282]
app.py

from flask import Flask
from celery import Celery
from flask import  Flask, request, render_template, url_for, redirect, current_app 
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.sql import func
from sqlalchemy import desc
app = Flask(__name__)

celery = Celery(
    __name__,
    broker="redis://127.0.0.1:6379/0",
    backend="redis://127.0.0.1:6379/0"
)

#configuring the database
app.config['SQLALCHEMY_DATABASE_URI']= 'sqlite:///test.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS']=False

#initializing sqlalchemy
db=SQLAlchemy(app)

app.app_context().push()

#creating of the model
class Note(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    text = db.Column(db.String(100))
    description = db.Column(db.String(200))
    complete = db.Column(db.Boolean())
    comments = db.Column(db.String(200))
    date = db.Column(db.DateTime(timezone=True), default=func.now())

 
#home route
@app.route('/')
def home():
    # making the data to render from a descending order according to the datetime
    incomplete = Note.query.filter_by(complete=False).order_by(desc(Note.date)).all()
    complete = Note.query.filter_by(complete=True).order_by(desc(Note.date)).all()

    return render_template('home.html', incomplete=incomplete, complete=complete)

#route for adding todos
@app.route('/add', methods=['POST'])
def add():
    # task = Note.query.get_or_404(id)
    with app.app_context():
        task_add.delay()
    # response = {
    #     'task_id':result.taks_id,
    #     'task_name':result.task_name
    # }
    return redirect (url_for('home'))

#route to mark completed task
@app.route('/complete/<id>')
def complete(id):
    task_complete.delay(id)
    return redirect (url_for('home'))

@celery.task(name="Todo-Add")
def task_add():
    with app.app_context():
        task = Note(text=request.form['todoitem'],
                    description=request.form['tododesc'],
                    comments=request.form['todocomm'],
                    complete=False)
        db.session.add(task)
        db.session.commit()

@celery.task(name="Todo-Completion")
def task_complete(id):
    note = Note.query.filter_by(id=int(id)).first()
    note.complete = True
    db.session.commit()

#initiating the flask framework
if __name__ == "__main__":
    app.run(debug=True)

----------------------------------------------------------------------------------------------------------
Errorr at celery worker

[tasks]
  . Todo-Add
  . Todo-Completion

[2023-10-10 21:13:06,887: INFO/MainProcess] Connected to redis://127.0.0.1:6379/0
[2023-10-10 21:13:06,912: INFO/MainProcess] mingle: searching for neighbors
[2023-10-10 21:13:07,967: INFO/MainProcess] mingle: all alone
[2023-10-10 21:13:08,101: INFO/MainProcess] celery@anandahiremath-mac ready.
[2023-10-10 21:13:40,280: INFO/MainProcess] Task Todo-Add[50d51767-c4dc-44dc-af9c-2c33afbae2d3] received
[2023-10-10 21:13:40,313: ERROR/ForkPoolWorker-8] Task Todo-Add[50d51767-c4dc-44dc-af9c-2c33afbae2d3] raised unexpected: RuntimeError('Working outside of request context.\n\nThis typically means that you attempted to use functionality that needed\nan active HTTP request. Consult the documentation on testing for\ninformation about how to avoid this problem.')
Traceback (most recent call last):
  File "/Users/anandahiremath/Documents/myLearn/flaskRedis/flask-celery/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/anandahiremath/Documents/myLearn/flaskRedis/flask-celery/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/anandahiremath/Documents/myLearn/flaskRedis/app.py", line 83, in task_add
    task = Note(text=request.form['todoitem'],
  File "/Users/anandahiremath/Documents/myLearn/flaskRedis/flask-celery/lib/python3.10/site-packages/werkzeug/local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "/Users/anandahiremath/Documents/myLearn/flaskRedis/flask-celery/lib/python3.10/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request. Consult the documentation on testing for
information about how to avoid this problem.

**Comment by xSAVIKx** [comment]
@AnandHiremath, you won't be able to run Celery with Cloud Functions as they do not have active CPU after the request is gone. That's what the error states:

```
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request. Consult the documentation on testing for
information about how to avoid this problem.
```

You best possible approach here would be to jump off to Cloud Run and use its `CPU always allocated` feature (check out the docs here: https://cloud.google.com/run/docs/configuring/cpu-allocation).

**Comment by HKWinterhalter** [comment]
What @xSAVIKx says is correct, so you may try this with Cloud Run and CPU allocation enabled to see if that resolves the issue. I cannot speak to if there are Celery settings to work around this.
